//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TargetTypeId { get; set; }
        public int ReasonId { get; set; }
        public int BookId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> TargetId { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ComplaintReasons ComplaintReasons { get; set; }
        public virtual ComplaintTargetTypes ComplaintTargetTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
