//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_UPEntities : DbContext
    {
        public DB_UPEntities()
            : base("name=DB_UPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationStatuses> ApplicationStatuses { get; set; }
        public virtual DbSet<AuthorApplications> AuthorApplications { get; set; }
        public virtual DbSet<BookGenres> BookGenres { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<ComplaintReasons> ComplaintReasons { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<ComplaintTargetTypes> ComplaintTargetTypes { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ReadingLists> ReadingLists { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusBooks> StatusBooks { get; set; }
        public virtual DbSet<UnfreezeApplications> UnfreezeApplications { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
